### ISSUE TITLE
lxc-attach error when I execute : vagrant destroy -f

### ISSUE THREAD

**Issue by harobed** [fgrehm/vagrant-lxc#295]
If I execute ```vagrant destroy -f``` I've this error :

```
$ vagrant destroy -f
==> default: Destroying VM and associated drives...
==> default: Running cleanup tasks for 'shell' provisioner...
==> default: Updating /etc/hosts file on active guest machines...
==> default: Updating /etc/hosts file on host machine (password may be required)...
/opt/vagrant/embedded/gems/gems/childprocess-0.5.3/lib/childprocess/abstract_process.rb:45:in `initialize': all arguments must be String: ["/usr/bin/sudo", "lxc-attach", "--name", nil, "--namespaces", "NETWORK", "--", "/sbin/ip", "-4", "addr", "show", "scope", "global", "eth0"] (ArgumentError)
	from /opt/vagrant/embedded/gems/gems/childprocess-0.5.3/lib/childprocess.rb:19:in `new'
	from /opt/vagrant/embedded/gems/gems/childprocess-0.5.3/lib/childprocess.rb:19:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/subprocess.rb:64:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/subprocess.rb:22:in `execute'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/sudo_wrapper.rb:71:in `block in raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/sudo_wrapper.rb:70:in `raw'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/sudo_wrapper.rb:37:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/sudo_wrapper.rb:35:in `execute'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/sudo_wrapper.rb:15:in `run'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/driver/cli.rb:132:in `run'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/driver/cli.rb:109:in `attach'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/driver.rb:117:in `attach'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/action/fetch_ip_with_lxc_attach.rb:35:in `get_container_ip_from_ip_addr'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/action/fetch_ip_with_lxc_attach.rb:25:in `block in assigned_ip'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/action/fetch_ip_with_lxc_attach.rb:24:in `assigned_ip'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/action/fetch_ip_with_lxc_attach.rb:14:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:196:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:173:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:403:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `action'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-lxc-1.0.0.alpha.2/lib/vagrant-lxc/provider.rb:73:in `ssh_info'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:367:in `ssh_info'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/hosts_file.rb:105:in `get_ip_address'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/hosts_file.rb:84:in `get_hosts_file_entry'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/hosts_file.rb:78:in `block in update_content'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/hosts_file.rb:78:in `map'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/hosts_file.rb:78:in `update_content'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/hosts_file.rb:68:in `update_file'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/hosts_file.rb:58:in `update_host'
	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0/lib/vagrant-hostmanager/action/update_all.rb:47:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:196:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:173:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:434:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/commands/destroy/command.rb:31:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/plugin/v2/command.rb:220:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/commands/destroy/command.rb:30:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:252:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.6.3/bin/vagrant:166:in `<main>'
```

**Comment by fgrehm** [comment]
Using latest code from the current `next` branch available on github under Ubuntu 14.04 and vagrant 1.7.2 I can't reproduce this.

Please try upgrading and reopen if it doesnt work for you. Thanks in advance!
