### ISSUE TITLE
Packaging vagrant lxc container

### ISSUE THREAD

**Issue by visibilityspots** [fgrehm/vagrant-lxc#328]
Based on http://fabiorehm.com/blog/2013/07/18/crafting-your-own-vagrant-lxc-base-box/ I am trying to get a clean centos lxc container packaged to be used within vagrant.

metadata.json:

``` json
{
  "name": "vagrant-lxc-centos",
  "provider": "lxc",
  "version":  "1.0.0",
  "built-on": "Wed Oct 11 15:30:00 UTC 2014"
}
```

lxc-template.bkp comes from https://github.com/fgrehm/vagrant-lxc-base-boxes/blob/master/common/lxc-template.bkp

Everthing seems to be going pretty well till I tried to get that box up and running in vagrant, any ideas what I am overlooking?

For the moment it's just a fresh generated centos container. I am aware of the https://github.com/fgrehm/vagrant-lxc-base-boxes but I want to get a custom box provisioned to our devs based on our internal requirements.

Nowadays this happens through virtualbox but I want to get it running on lxc :)

``` bash
vagrant up --provider=lxc
Bringing machine 'default' up with 'lxc' provider...
==> default: Box 'vagrant-lxc-centos' could not be found. Attempting to find and install...
    default: Box Provider: lxc
    default: Box Version: >= 0
==> default: Adding box 'vagrant-lxc-centos' (v0) for provider: lxc
    default: Downloading: file:///tmp/vagrant-lxc-centos6/vagrant-lxc-centos.box
==> default: Successfully added box 'vagrant-lxc-centos' (v0) for 'lxc'!
==> default: Importing base box 'vagrant-lxc-centos'...
==> default: Setting up mount entries for shared folders...
/home/Jan/.vagrant.d/gems/gems/vagrant-lxc-1.0.0/lib/vagrant-lxc/driver.rb:43:in `rootfs_path': undefined method `[]' for nil:NilClass (NoMethodError)
    from /home/Jan/.vagrant.d/gems/gems/vagrant-lxc-1.0.0/lib/vagrant-lxc/driver.rb:75:in `share_folder'
    from /home/Jan/.vagrant.d/gems/gems/vagrant-lxc-1.0.0/lib/vagrant-lxc/synced_folder.rb:41:in `block in prepare'
    from /home/Jan/.vagrant.d/gems/gems/vagrant-lxc-1.0.0/lib/vagrant-lxc/synced_folder.rb:21:in `each'
    from /home/Jan/.vagrant.d/gems/gems/vagrant-lxc-1.0.0/lib/vagrant-lxc/synced_folder.rb:21:in `prepare'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/synced_folders.rb:80:in `block in call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/synced_folders.rb:78:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/synced_folders.rb:78:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/Jan/.vagrant.d/gems/gems/vagrant-lxc-1.0.0/lib/vagrant-lxc/action/prepare_nfs_valid_ids.rb:14:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:160:in `handle'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:42:in `block in call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in `lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:41:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/env_set.rb:19:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/provision.rb:80:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/Jan/.vagrant.d/gems/gems/vagrant-lxc-1.0.0/lib/vagrant-lxc/action/create.rb:37:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /home/Jan/.vagrant.d/gems/gems/vagrant-lxc-1.0.0/lib/vagrant-lxc/action/handle_box_metadata.rb:41:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:196:in `action_raw'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:173:in `block in action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in `lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

```

**Comment by kupferk** [comment]
I have the very same problem, both on Fedora 21 and on Ubuntu 14.04 as the host systems. Even when I use the pre-built images, I get that error:

```
# vagrant init fgrehm/trusty64-lxc
# vagrant up --provider=lxc
==> default: Box 'fgrehm/trusty64-lxc' could not be found. Attempting to find and install...
    default: Box Provider: lxc
    default: Box Version: >= 0
==> default: Loading metadata for box 'fgrehm/trusty64-lxc'
    default: URL: https://atlas.hashicorp.com/fgrehm/trusty64-lxc
==> default: Adding box 'fgrehm/trusty64-lxc' (v1.2.0) for provider: lxc
    default: Downloading: https://atlas.hashicorp.com/fgrehm/boxes/trusty64-lxc/versions/1.2.0/providers/lxc.box
==> default: Successfully added box 'fgrehm/trusty64-lxc' (v1.2.0) for 'lxc'!
==> default: Importing base box 'fgrehm/trusty64-lxc'...
==> default: Checking if box 'fgrehm/trusty64-lxc' is up to date...
==> default: Setting up mount entries for shared folders...
/home/kaya/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/driver.rb:48:in `rootfs_path': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/kaya/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/driver.rb:80:in `share_folder'
	from /home/kaya/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/synced_folder.rb:41:in `block in prepare'
	from /home/kaya/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/synced_folder.rb:21:in `each'
	from /home/kaya/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/synced_folder.rb:21:in `prepare'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:80:in `block in call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:78:in `each'
...
```

Any help would be highly appreciated!

**Comment by fgrehm** [comment]
@kupferk please try the new version of the plugin and open up a new issue in case things are not working fine for you!

**Comment by kupferk** [comment]
Thanks a lot! I will test it this week-end.

**Comment by kupferk** [comment]
@fgrehm sorry for the late answer, I was too busy to check. But it works now like a charm! Thanks a lot!
