### ISSUE TITLE
Override default network settings: lxc__bridge_name (KeyError)

### ISSUE THREAD

**Issue by gotlium** [fgrehm/vagrant-lxc#387]
```
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network :private_network, ip: APP_HOST

    config.vm.provider :parallels do |vb, override|
        override.vm.box = "parallels/ubuntu-14.04"
    end

    config.vm.provider :lxc do |lxc, override|
        override.vm.network "private_network", ip: "192.168.3.100", lxc__bridge_name: 'vlxcbr1'
        override.vm.box = "fgrehm/trusty64-lxc"
    end
end
```

Error message: ~/.vagrant.d/gems/gems/vagrant-lxc-1.1.0/lib/vagrant-lxc/action/private_networks.rb:31:in `fetch': key not found: :lxc__bridge_name (KeyError)

**Comment by gotlium** [comment]
I think you can check and if bridge is not defined - setup it automatically. If bridge is exists you can raise error, or increase counter and use new bridge.

So when config.vm.network defined outer config.vm.provider :lxc block, I get following error:

    ==> default: Setting up private networks...
    There was an error executing ["sudo", "/root/.vagrant.d/gems/gems/vagrant-lxc-1.1.0/scripts/pipework",     "vlxcbr1", "vm", "192.168.2.100/24"]
    For more information on the failure, enable detailed logging by setting
    the environment variable VAGRANT_LOG to DEBUG .

stdout: `Could not locate cgroup mount point.`

Part 2:
When override.vm.network "private_network" was removed, and configured port forwarding, I still got: `fetch': key not found: :lxc__bridge_name (KeyError)

Really very strange behavior.

**Comment by mwild1** [comment]
This issue affects me too, as soon as I simply try to set a static IP with:

```
machine.vm.network "private_network", ip: "192.168.51.4"
```

I have vagrant 1.8.1, with vagrant-lxc 1.2.1.

**Comment by alf239** [comment]
Same here, vagrant 1.8.4, lxc 2.0.1, vagrant-lxc 1.2.1

```
An unexpected error occurred when executing the action on the
'master' machine. Please report this as a bug:

key not found: :lxc__bridge_name

/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/private_networks.rb:32:in `fetch'
/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/private_networks.rb:32:in `block in configure_private_networks'
/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/private_networks.rb:25:in `each'
/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/private_networks.rb:25:in `find'
/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/private_networks.rb:25:in `configure_private_networks'
/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/private_networks.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/forward_ports.rb:29:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/warn_networks.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/set_hostname.rb:16:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/prepare_nfs_settings.rb:15:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/prepare_nfs_valid_ids.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:49:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/env_set.rb:19:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/box_check_outdated.rb:78:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/create.rb:33:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/home/alf/.vagrant.d/gems/gems/vagrant-lxc-1.2.1/lib/vagrant-lxc/action/handle_box_metadata.rb:41:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:225:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:200:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/environment.rb:561:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:186:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/machine.rb:186:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

```

**Comment by alf239** [comment]
@mwild1, you need to specify the bridge name explicitly:

> 
> ### Private Networks [EXPERIMENTAL]
> 
> Starting with vagrant-lxc 1.1.0, there is some rudimentary support for configuring
> [Private Networks](https://docs.vagrantup.com/v2/networking/private_network.html)
> by leveraging the [pipework](https://github.com/jpetazzo/pipework) project.
> 
> On its current state, there is a requirement for setting the bridge name that
> will be created and will allow your machine to comunicate with the container
> 
> For example:
> 
> ```ruby
> Vagrant.configure("2") do |config|
>   config.vm.network "private_network", ip: "192.168.2.100", lxc__bridge_name: 'vlxcbr1'
> end
> ```
> 
> Will create a new `veth` device for the container and will set up (or reuse)
> a `vlxcbr1` bridge between your machine and the `veth` device. Once the last
> vagrant-lxc container attached to the bridge gets `vagrant halt`ed, the plugin
> will delete the bridge.

(from the README.md)

**Comment by fgrehm** [comment]
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:
