### ISSUE TITLE
can't start lxc vagrant on ubuntu 18.04

### ISSUE THREAD

**Issue by fizyk** [fgrehm/vagrant-lxc#465]
I'm getting hit by `Make sure you have the package around and try removing the [The `lxc` package does not seem to be installed or `lxc-create` is not accessible on the PATH.](https://github.com/fgrehm/vagrant-lxc/wiki/Troubleshooting#im-seeing-a-the-lxc-package-does-not-seem-to-be-installed-or-is-not-accessible-on-the-path-error)

The only problem is, that I do not have the requiretty in the sudoers file.

```
 INFO global: Vagrant version: 2.1.1
 INFO global: Ruby version: 2.4.4
 INFO global: RubyGems version: 2.6.14.1
 INFO global: VAGRANT_LOG="debug"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/embedded"
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/bin/vagrant"
 WARN global: resolv replacement has not been enabled!
 INFO global: Plugins:
 INFO global:   - vagrant-lxc = [installed: 1.4.1 constraint: > 0]
DEBUG bundler: Current generated plugin dependency list: [<Gem::Dependency type=:runtime name="vagrant-lxc" requirements="> 0">]
DEBUG bundler: Generating new builtin set instance.
DEBUG bundler: Generating new plugin set instance. Skip gems - []
DEBUG bundler: Activating solution set: ["vagrant-lxc-1.4.1"]
DEBUG bundler: Activating gem vagrant-lxc-1.4.1
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/bsd/plugin.rb
 INFO manager: Registered plugin: BSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/suse/plugin.rb
 INFO manager: Registered plugin: SUSE host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/darwin/plugin.rb
 INFO manager: Registered plugin: Mac OS X host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/null/plugin.rb
 INFO manager: Registered plugin: null host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/linux/plugin.rb
 INFO manager: Registered plugin: Linux host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/arch/plugin.rb
 INFO manager: Registered plugin: Arch host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/alt/plugin.rb
 INFO manager: Registered plugin: ALT Platform host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/windows/plugin.rb
 INFO manager: Registered plugin: Windows host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/hosts/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD host
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/kernel_v2/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/bsd/plugin.rb
 INFO manager: Registered plugin: BSD-based guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/haiku/plugin.rb
 INFO manager: Registered plugin: Haiku guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/fedora/plugin.rb
 INFO manager: Registered plugin: Fedora guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/photon/plugin.rb
 INFO manager: Registered plugin: VMware Photon guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/pld/plugin.rb
 INFO manager: Registered plugin: PLD Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/dragonflybsd/plugin.rb
 INFO manager: Registered plugin: DragonFly BSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/kali/plugin.rb
 INFO manager: Registered plugin: Kali guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/amazon/plugin.rb
 INFO manager: Registered plugin: Amazon Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/ubuntu/plugin.rb
 INFO manager: Registered plugin: Ubuntu guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/openbsd/plugin.rb
 INFO manager: Registered plugin: OpenBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/atomic/plugin.rb
 INFO manager: Registered plugin: Atomic Host guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/coreos/plugin.rb
 INFO manager: Registered plugin: CoreOS guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/suse/plugin.rb
 INFO manager: Registered plugin: SUSE guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/darwin/plugin.rb
 INFO manager: Registered plugin: Darwin guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/netbsd/plugin.rb
 INFO manager: Registered plugin: NetBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/omnios/plugin.rb
 INFO manager: Registered plugin: OmniOS guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/smartos/plugin.rb
 INFO manager: Registered plugin: SmartOS guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/funtoo/plugin.rb
 INFO manager: Registered plugin: Funtoo guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/linux/plugin.rb
 INFO manager: Registered plugin: Linux guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/elementary/plugin.rb
 INFO manager: Registered plugin: Elementary guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/arch/plugin.rb
 INFO manager: Registered plugin: Arch guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/alt/plugin.rb
 INFO manager: Registered plugin: ALT Platform guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/mint/plugin.rb
 INFO manager: Registered plugin: Mint guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/solaris/plugin.rb
 INFO manager: Registered plugin: Solaris guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/nixos/plugin.rb
 INFO manager: Registered plugin: NixOS guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/tinycore/plugin.rb
 INFO manager: Registered plugin: TinyCore Linux guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/debian/plugin.rb
 INFO manager: Registered plugin: Debian guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/windows/plugin.rb
 INFO manager: Registered plugin: Windows guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/trisquel/plugin.rb
 INFO manager: Registered plugin: Trisquel guest
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/solaris11/plugin.rb
 INFO manager: Registered plugin: Solaris 11 guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/guests/esxi/plugin.rb
 INFO manager: Registered plugin: ESXi guest.
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/kernel_v1/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/provisioners/ansible/plugin.rb
 INFO manager: Registered plugin: ansible
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/provisioners/cfengine/plugin.rb
 INFO manager: Registered plugin: CFEngine Provisioner
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/provisioners/docker/plugin.rb
 INFO manager: Registered plugin: docker
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/provisioners/file/plugin.rb
 INFO manager: Registered plugin: file
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/provisioners/puppet/plugin.rb
 INFO manager: Registered plugin: puppet
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/provisioners/shell/plugin.rb
 INFO manager: Registered plugin: shell
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/provisioners/chef/plugin.rb
 INFO manager: Registered plugin: chef
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/provisioners/salt/plugin.rb
 INFO manager: Registered plugin: salt
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/pushes/local-exec/plugin.rb
 INFO manager: Registered plugin: local-exec
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/pushes/atlas/plugin.rb
 INFO manager: Registered plugin: atlas
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/pushes/ftp/plugin.rb
 INFO manager: Registered plugin: ftp
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/pushes/noop/plugin.rb
 INFO manager: Registered plugin: noop
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/pushes/heroku/plugin.rb
 INFO manager: Registered plugin: heroku
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/communicators/winssh/plugin.rb
 INFO manager: Registered plugin: windows ssh communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/communicators/winrm/plugin.rb
 INFO manager: Registered plugin: winrm communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/communicators/ssh/plugin.rb
 INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/plugin/plugin.rb
 INFO manager: Registered plugin: plugin command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/cap/plugin.rb
 INFO manager: Registered plugin: cap command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/snapshot/plugin.rb
 INFO manager: Registered plugin: snapshot command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/rdp/plugin.rb
 INFO manager: Registered plugin: rdp command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/global-status/plugin.rb
 INFO manager: Registered plugin: global-status command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/list-commands/plugin.rb
 INFO manager: Registered plugin: list-commands command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/halt/plugin.rb
 INFO manager: Registered plugin: halt command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/help/plugin.rb
 INFO manager: Registered plugin: help command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/powershell/plugin.rb
 INFO manager: Registered plugin: powershell command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/port/plugin.rb
 INFO manager: Registered plugin: port command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/package/plugin.rb
 INFO manager: Registered plugin: package command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/up/plugin.rb
 INFO manager: Registered plugin: up command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/suspend/plugin.rb
 INFO manager: Registered plugin: suspend command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/destroy/plugin.rb
 INFO manager: Registered plugin: destroy command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/login/plugin.rb
 INFO manager: Registered plugin: vagrant-login
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/provider/plugin.rb
 INFO manager: Registered plugin: provider command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/push/plugin.rb
 INFO manager: Registered plugin: push command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/resume/plugin.rb
 INFO manager: Registered plugin: resume command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/status/plugin.rb
 INFO manager: Registered plugin: status command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/validate/plugin.rb
 INFO manager: Registered plugin: validate command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/ssh_config/plugin.rb
 INFO manager: Registered plugin: ssh-config command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/init/plugin.rb
 INFO manager: Registered plugin: init command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/box/plugin.rb
 INFO manager: Registered plugin: box command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/provision/plugin.rb
 INFO manager: Registered plugin: provision command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/version/plugin.rb
 INFO manager: Registered plugin: version command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/reload/plugin.rb
 INFO manager: Registered plugin: reload command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/ssh/plugin.rb
 INFO manager: Registered plugin: ssh command
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/synced_folders/smb/plugin.rb
 INFO manager: Registered plugin: SMB synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/synced_folders/nfs/plugin.rb
 INFO manager: Registered plugin: NFS synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/synced_folders/rsync/plugin.rb
 INFO manager: Registered plugin: RSync synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/providers/hyperv/plugin.rb
 INFO manager: Registered plugin: Hyper-V provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/providers/virtualbox/plugin.rb
 INFO manager: Registered plugin: VirtualBox provider
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/providers/docker/plugin.rb
 INFO manager: Registered plugin: docker-provider
 INFO global: Loading plugins!
DEBUG global: Loading plugin `vagrant-lxc` with default require: `vagrant-lxc`
 INFO manager: Registered plugin: vagrant-lxc
DEBUG global: Successfully loaded plugin `vagrant-lxc`.
 INFO vagrant: `vagrant` invoked: ["up"]
DEBUG vagrant: Creating Vagrant environment
 INFO environment: Environment initialized (#<Vagrant::Environment:0x00000000016c0448>)
 INFO environment:   - cwd: /home/fizyk/workspace/sitodsp-provisioner
 INFO environment: Home path: /home/fizyk/.vagrant.d
DEBUG environment: Effective local data path: /home/fizyk/workspace/sitodsp-provisioner/.vagrant
 INFO environment: Local data path: /home/fizyk/workspace/sitodsp-provisioner/.vagrant
DEBUG environment: Creating: /home/fizyk/workspace/sitodsp-provisioner/.vagrant
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Builder:0x0000000001d80e90>
 INFO environment: Running hook: environment_load
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x0000000001689a60>
DEBUG checkpoint_client: starting plugin check
 INFO cli: CLI: [] "up" []
DEBUG checkpoint_client: plugin check complete
DEBUG cli: Invoking command class: VagrantPlugins::CommandUp::Command []
DEBUG checkpoint_client: no information received from checkpoint
DEBUG command: 'Up' each target VM...
 INFO loader: Set :root = ["#<Pathname:/home/fizyk/workspace/sitodsp-provisioner/Vagrantfile>"]
DEBUG loader: Populating proc cache for #<Pathname:/home/fizyk/workspace/sitodsp-provisioner/Vagrantfile>
DEBUG loader: Load procs for pathname: /home/fizyk/workspace/sitodsp-provisioner/Vagrantfile
 INFO root: Version requirements from Vagrantfile: [">= 1.7.2"]
 INFO root:   - Version requirements satisfied!
 INFO loader: Loading configuration in order: [:home, :root]
DEBUG loader: Loading from: root (evaluating)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
DEBUG command: Getting target VMs for command. Arguments:
DEBUG command:  -- names: ["devbox"]
DEBUG command:  -- options: {:provider=>nil}
DEBUG command: Finding machine that match name: devbox
 INFO command: Active machine found with name devbox. Using provider: lxc
 INFO environment: Getting machine: devbox (lxc)
 INFO environment: Uncached load of machine.
 INFO loader: Set "15425160_machine_devbox" = ["[\"2\", #<Proc:0x0000000002506e08@/home/fizyk/workspace/sitodsp-provisioner/Vagrantfile:17>]"]
DEBUG loader: Populating proc cache for ["2", #<Proc:0x0000000002506e08@/home/fizyk/workspace/sitodsp-provisioner/Vagrantfile:17>]
 INFO loader: Loading configuration in order: [:home, :root, "15425160_machine_devbox"]
DEBUG loader: Loading from: root (cache)
DEBUG loader: Loading from: 15425160_machine_devbox (evaluating)
DEBUG provisioner: Provisioner defined: 
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO box_collection: Box found: debian/stretch64 (lxc)
 INFO environment: Running hook: authenticate_box_url
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/fizyk/workspace/sitodsp-provisioner>]
DEBUG host: Trying: gentoo
DEBUG host: Trying: suse
DEBUG host: Trying: darwin
DEBUG host: Trying: slackware
DEBUG host: Trying: arch
DEBUG host: Trying: alt
DEBUG host: Trying: redhat
DEBUG host: Trying: freebsd
DEBUG host: Trying: bsd
DEBUG host: Trying: null
DEBUG host: Trying: linux
 INFO host: Detected: linux!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: authenticate_box_url #<Vagrant::Action::Builder:0x000000000228a5d0>
 INFO warden: Calling IN action: #<VagrantPlugins::LoginCommand::AddAuthentication:0x0000000002d61698>
DEBUG client: No authentication token in environment or /home/fizyk/.vagrant.d/data/vagrant_login_token
 INFO warden: Calling OUT action: #<VagrantPlugins::LoginCommand::AddAuthentication:0x0000000002d61698>
 INFO loader: Set :"15425160_vm_devbox_debian/stretch64_lxc" = ["[\"2\", #<Proc:0x0000000001d6a7f8>]"]
DEBUG loader: Populating proc cache for ["2", #<Proc:0x0000000001d6a7f8>]
 INFO loader: Loading configuration in order: [:home, :root, "15425160_machine_devbox", :"15425160_vm_devbox_debian/stretch64_lxc"]
DEBUG loader: Loading from: root (cache)
DEBUG loader: Loading from: 15425160_machine_devbox (cache)
DEBUG loader: Loading from: 15425160_vm_devbox_debian/stretch64_lxc (evaluating)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO machine: Initializing machine: devbox
 INFO machine:   - Provider: Vagrant::LXC::Provider
 INFO machine:   - Box: #<Vagrant::Box:0x0000000002d95bf0>
 INFO machine:   - Data dir: /home/fizyk/workspace/sitodsp-provisioner/.vagrant/machines/devbox/lxc
 INFO subprocess: Starting process: ["/usr/bin/sudo", "/usr/local/bin/vagrant-lxc-wrapper", "which", "lxc-create"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: sudo: nie udało się wywołać /usr/local/bin/vagrant-lxc-wrapper: Nie ma takiego pliku ani katalogu
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 1
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000000002e08010>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::LXC::Errors::LxcNotInstalled: The `lxc` package does not seem to be installed or `lxc-create` is not accessible on the PATH.>
ERROR vagrant: The `lxc` package does not seem to be installed or `lxc-create` is not accessible on the PATH.
ERROR vagrant: /home/fizyk/.vagrant.d/gems/2.4.4/gems/vagrant-lxc-1.4.1/lib/vagrant-lxc/provider.rb:31:in `rescue in ensure_lxc_installed!'
/home/fizyk/.vagrant.d/gems/2.4.4/gems/vagrant-lxc-1.4.1/lib/vagrant-lxc/provider.rb:27:in `ensure_lxc_installed!'
/home/fizyk/.vagrant.d/gems/2.4.4/gems/vagrant-lxc-1.4.1/lib/vagrant-lxc/provider.rb:23:in `initialize'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:134:in `new'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:134:in `initialize'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/vagrantfile.rb:79:in `new'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/vagrantfile.rb:79:in `machine'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/environment.rb:700:in `machine'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/v2/command.rb:186:in `each'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/up/command.rb:87:in `execute'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/cli.rb:54:in `execute'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/environment.rb:275:in `cli'
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/bin/vagrant:156:in `<main>'
 INFO interface: error: The `lxc` package does not seem to be installed or `lxc-create` is not accessible on the PATH.
The `lxc` package does not seem to be installed or `lxc-create` is not accessible on the PATH.
 INFO interface: Machine: error-exit ["Vagrant::LXC::Errors::LxcNotInstalled", "The `lxc` package does not seem to be installed or `lxc-create` is not accessible on the PATH."]
```

lxc is creted and lxc-create is in path.

I recall I had similar issues in ubuntu 17.10, but then I reverted back to the ubuntu delivered vagrant (which was <2) now that system also provides vagrant 2.0.2 I'm pretty stuck, unless I downgrade the vagrant manually and try that.

**Comment by fizyk** [comment]
okay, had to remove old vagrant-lxc-sudoers file would be good if it was possible to regenerate it automatically (ie by vagrant lxc sudoers)

**Comment by hsoft** [comment]
@fizyk Yeah, the whole sudoers mechanism is a bit icky. But hopefully, as people adopt unprivileged containers (and thus don't require sudoing), this issue is going to fade away.
